### ISSUE TITLE
Performance optimisations

### ISSUE THREAD

**Issue by melish** [eaudeweb/scoreboard.visualization#119]
* [ ] dimension_labels vs dimension_value_metadata vs dimension_options (labels.sparql)
* [ ] possibly preload all labels for all code lists (server-side or even in the browser, to reduce the number of XHR's)

* [ ] possibly replace dimension_value_metadata for annotations
Dimension_value_metadata uses dimension_option_metadata.sparql, which  has a lot of OPTIONAL clauses and was designed for indicators + sources

* [x] check if relation to dataset and observations is mandatory in dimension_label.sparql (i.e. as in labels.sparql)

* [x] preload js and css resources using plone - #122

* [x] optimize datapoints_cp (country profile & ranking) -  #135 

* [x] optimize dimension_options - #133 
* [ ] preload and cache dad-prop:membership, dad-prop:order for indicators and breakdowns - instead of using optional clauses
* [ ] possibly replace inline in sparql queries the indirect relation to a indicator-group or breakdown-group (dad-prop:grouped-using) with the URI list of indicators/breakdowns

* [ ] replace inline dimensions grouped by a group-dimension: 
instead of:
```
 ?observation ?filter_1_dimension ?filter_1_option_child .
  ?filter_1_dimension dad-prop:grouped-using dad-prop:indicator-group .
```
use
```
 ?observation dad-prop:indicator ?filter_1_option_child.
```
